version: '0.0.1'

services:

    web:  
        build: ./project
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./project:/usr/src/app
        ports:
            - 8004:8000
        environment:
            - DATABASE_URL=postgresql+asyncpg://petProjectsUser:password@db:5432/myCodeHedgehogDB
        depends_on:
            - db

    db:
        image: postgres:14
        expose:
            - 5432
        environment:
            - POSTGRES_USER=petProjectsUser
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=myCodeHedgehogDB
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports: 
            - 5432:5432

volumes:
    pg-data:
