"""changed users

Revision ID: 25a3ee0f9951
Revises: 8829026d4397
Create Date: 2022-04-11 02:04:17.751934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a3ee0f9951'
down_revision = '8829026d4397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
