"""added topic model

Revision ID: 581ff6783eab
Revises: 77d6d7d91958
Create Date: 2022-04-19 23:19:39.002497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581ff6783eab'
down_revision = '77d6d7d91958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
